version: "3"

services:
  app:
    image: address_change_api
    build:
      context: .
    container_name: address_change_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: poetry run gunicorn app.wsgi:application --bind 0.0.0.0:8000
    # sh -c "python manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:latest # nginx 서비스에서 사용할 도커 이미지
    container_name: web_server
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on: # 서비스 간의 종속성 표현
      - app
