# Generated by Django 3.0.5 on 2021-06-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210612_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='t_task',
        ),
        migrations.AddField(
            model_name='todo',
            name='task',
            field=models.TextField(null=True),
        ),
    ]
