# Generated by Django 3.0.5 on 2021-06-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210612_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='highlight',
            field=models.IntegerField(default=0),
        ),
    ]
