# Generated by Django 3.0.5 on 2021-06-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
