# Generated by Django 3.0.5 on 2021-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='do_yn',
            field=models.IntegerField(default=0),
        ),
    ]
